<?php 
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array(
	'key' => 'group_61e0218f56e27',
	'title' => 'FAQs',
	'fields' => array(
		array(
			'key' => 'field_61e0219f32484',
			'label' => 'FAQ-Eintrag',
			'name' => 'faq-eintrag',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'acfe_settings' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_61e021db32485',
					'label' => 'Titel',
					'name' => 'titel',
					'type' => 'text',
					'instructions' => '[DL] [DL-ENTRUMPELUNG] [DASDERUNTERNEHMENWORTE] [DIEFIRMAWORTE] [UNDWORTE] [SOWIEWORTE] [ISTWORTE] [AUFLOESUNGWORTE] [RAEUMUNGWORTE] [ENTRUEMPELUNGWORTE] [DL-ENTRUMPELUNG]  [SCHNELLWORTE] [PROFIWORTE] [ORDENTLICHWORTE] [PARTNERWORTE] [HELFENWORTE] [MACHTWORTE] [BRAUCHWORTE] [ALLEINWORTE] [RAUMWORTE] [SCHAFFENWORTE]',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_61e021fe32486',
					'label' => 'Faq-Inhalt',
					'name' => 'faq-inhalt',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
				array(
					'key' => 'faq_extension',
					'label' => 'Faq-Inhalt-Extension',
					'name' => 'faq-extension',
					'type' => 'wysiwyg',
					'instructions' => 'Wenn der Inhalt 300 Zeichen überschreitet hier weiteren Text einfügen',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-hauptseiten.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-startseite.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
));
endif;