<?php

namespace SeopressComposer\Services;

/**
 * Robots.txt Service
 * 
 * Generates a theme-native robots.txt with intelligent crawl directives
 * including AI/LLM crawler allowances for 2026 AI-SEO compliance.
 */
class RobotsTxtService
{
    public function __construct()
    {
        add_filter('robots_txt', [$this, 'generate_robots_txt'], 10, 2);
    }

    /**
     * Generate optimized robots.txt content
     */
    public function generate_robots_txt(string $output, bool $public): string
    {
        if (!$public) {
            return "User-agent: *\nDisallow: /\n";
        }

        $sitemap_url = home_url('/wp-sitemap.xml');
        $lines = [];

        // Main crawler directives
        $lines[] = '# robots.txt — Generated by seopress_composer Theme';
        $lines[] = '# Last updated: ' . date('Y-m-d');
        $lines[] = '';
        $lines[] = 'User-agent: *';
        $lines[] = 'Allow: /';
        $lines[] = 'Disallow: /wp-admin/';
        $lines[] = 'Allow: /wp-admin/admin-ajax.php';
        $lines[] = 'Disallow: /wp-includes/';
        $lines[] = 'Disallow: /wp-content/plugins/';
        $lines[] = 'Disallow: /wp-content/cache/';
        $lines[] = 'Disallow: /wp-json/';
        $lines[] = 'Disallow: /?s=';
        $lines[] = 'Disallow: /search/';
        $lines[] = 'Disallow: /*?replytocom=';
        $lines[] = 'Disallow: /tag/';
        $lines[] = 'Disallow: /author/';
        $lines[] = '';

        // AI/LLM Crawler Allowances (2026 AI-SEO Standard)
        $lines[] = '# AI/LLM Crawlers — Explicitly Allowed';
        $lines[] = 'User-agent: GPTBot';
        $lines[] = 'Allow: /';
        $lines[] = 'Disallow: /wp-admin/';
        $lines[] = '';
        $lines[] = 'User-agent: Google-Extended';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = 'User-agent: anthropic-ai';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = 'User-agent: Claude-Web';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = 'User-agent: PerplexityBot';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = 'User-agent: Applebot-Extended';
        $lines[] = 'Allow: /';
        $lines[] = '';

        // Sitemap
        $lines[] = '# Sitemaps';
        $lines[] = 'Sitemap: ' . esc_url($sitemap_url);
        $lines[] = 'Sitemap: ' . esc_url(home_url('/image-sitemap.xml'));
        $lines[] = '';

        // llms.txt reference
        $lines[] = '# AI Context File';
        $lines[] = '# See: ' . home_url('/llms.txt');
        $lines[] = '';

        return implode("\n", $lines);
    }
}
