<?php 
if( function_exists('acf_add_local_field_group') ):
	
acf_add_local_field_group(array(
	'key' => 'group_6078225d05dc4',
	'title' => 'Vorteile',
	'fields' => array(
		array(
			'key' => 'field_60783ee3f8a87',
			'label' => 'schlagworte',
			'name' => 'schlagworte',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_60783ef0f8a88',
					'label' => 'Schlagwort',
					'name' => 'schlagwort',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 60,
				),
				array(
					'key' => 'field_609138803c117',
					'label' => 'beschreibung',
					'name' => 'beschreibung',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 300,
					'rows' => 4,
					'new_lines' => '',
				),
				array(
					'key' => 'vorteile_icon',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'3. Generation' => '3. Generation',
						'Aktenvernichtung' => 'Aktenvernichtung',
						'Antiquitäten Ankauf' => 'Antiquitäten Ankauf',
						'Antiquitäten Briefmarke' => 'Antiquitäten Briefmarke',
						'Antiquitäten Dosen' => 'Antiquitäten Dosen',
						'Antiquitäten Gemälde' => 'Antiquitäten Gemälde',
						'Antiquitäten Krug' => 'Antiquitäten Krug',
						'Antiquitäten Münzen' => 'Antiquitäten Münzen',
						'Antiquitäten Orden' => 'Antiquitäten Orden',
						'Antiquitäten Religion' => 'Antiquitäten Religion',
						'Antiquitäten Teppich' => 'Antiquitäten Teppich',
						'Antiquitäten Uhr' => 'Antiquitäten Uhr',
						'Barzahlung' => 'Barzahlung',
						'Besen' => 'Besen',
						'Besichtigung' => 'Besichtigung',
						'Büroräumung' => 'Büroräumung',
						'Dachböden' => 'Dachböden',
						'Demontage' => 'Demontage',
						'Demontage/Montage' => 'Demontage/Montage',
						'Diskretion' => 'Diskretion',
						'Dummy' => 'Dummy',
						'E-Mail' => 'E-Mail',
						'Entrümpelungen' => 'Entrümpelungen',
						'Facebook' => 'Facebook',
						'FAQ' => 'FAQ',
						'FAQ (Glühbirne)' => 'FAQ (Glühbirne)',
						'Festpreisangebot (Variante 1)' => 'Festpreisangebot (Variante 1)',
						'Festpreisangebot (Variante 2)' => 'Festpreisangebot (Variante 2)',
						'Festpreisangebot (Variante 3)' => 'Festpreisangebot (Variante 3)',
						'Festpreisangebot (Variante 4)' => 'Festpreisangebot (Variante 4)',
						'Fixpreis' => 'Fixpreis',
						'Formular' => 'Formular',
						'Geschäftsauflösung' => 'Geschäftsauflösung',
						'Handwerker' => 'Handwerker',
						'Haus' => 'Haus',
						'Hotelräumung' => 'Hotelräumung',
						'Instagram' => 'Instagram',
						'Kellerräumung' => 'Kellerräumung',
						'Makler' => 'Makler',
						'Messie' => 'Messie',
						'Mobil' => 'Mobil',
						'Räumung (Variante 1)' => 'Räumung (Variante 1)',
						'Räumung (Variante 2)' => 'Räumung (Variante 2)',
						'Reinigung' => 'Reinigung',
						'Reinigung (Kübel)' => 'Reinigung (Kübel)',
						'Renovierung (Variante 1)' => 'Renovierung (Variante 1)',
						'Renovierung (Variante 2)' => 'Renovierung (Variante 2)',
						'Sicherheit (Regenschirm)' => 'Sicherheit (Regenschirm)',
						'Suche' => 'Suche',
						'Teilumzug' => 'Teilumzug',
						'Telefon' => 'Telefon',
						'Tipp' => 'Tipp',
						'Transport' => 'Transport',
						'Uhr' => 'Uhr',
						'Umelt' => 'Umelt',
						'Umzug' => 'Umzug',
						'Umzug/Übersiedelung' => 'Umzug/Übersiedelung',
						'Verlassenschaft (Variante 1)' => 'Verlassenschaft (Variante 1)',
						'Verlassenschaft (Variante 2)' => 'Verlassenschaft (Variante 2)',
						'Verschenken' => 'Verschenken',
						'Vorteile' => 'Vorteile',
						'Wertausgleich' => 'Wertausgleich',
						'Whatsapp' => 'Whatsapp',
						'Wohnungsauflösung' => 'Wohnungsauflösung',
						'Zusatzleistungen' => 'Zusatzleistungen',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-hauptseiten.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-startseite.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;