<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63b434ad6c640',
	'title' => 'Ablauf',
	'fields' => array(
		array(
			'key' => 'field_63b434e902975',
			'label' => 'Ablauf Blöcke',
			'name' => 'ablauf_blocke',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_63b4351502976',
					'label' => 'Ablauf 1',
					'name' => 'ablauf_1',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_63b436f090aa2',
							'label' => 'Überschrift',
							'name' => 'uberschrift',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Besichtigung',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63b436ff90aa3',
							'label' => 'text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Vor Ort beraten wir Sie persönlich und verschaffen uns einen Überblick über ihre Räumlichkeiten. Die Besichtigung ist für Sie vollkommen kostenlos und unverbindlich',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'acfe_textarea_code' => 0,
						),
						array(
							'key' => 'field_63b4383cb52a4',
							'label' => 'icon',
							'name' => 'icon',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'3. Generation' => '3. Generation',
								'Aktenvernichtung' => 'Aktenvernichtung',
								'Antiquitäten Ankauf' => 'Antiquitäten Ankauf',
								'Antiquitäten Briefmarke' => 'Antiquitäten Briefmarke',
								'Antiquitäten Dosen' => 'Antiquitäten Dosen',
								'Antiquitäten Gemälde' => 'Antiquitäten Gemälde',
								'Antiquitäten Krug' => 'Antiquitäten Krug',
								'Antiquitäten Münzen' => 'Antiquitäten Münzen',
								'Antiquitäten Orden' => 'Antiquitäten Orden',
								'Antiquitäten Religion' => 'Antiquitäten Religion',
								'Antiquitäten Teppich' => 'Antiquitäten Teppich',
								'Antiquitäten Uhr' => 'Antiquitäten Uhr',
								'Barzahlung' => 'Barzahlung',
								'Besichtigung' => 'Besichtigung',
								'Büroräumung' => 'Büroräumung',
								'Dachböden' => 'Dachböden',
								'Demontage' => 'Demontage',
								'Demontage/Montage' => 'Demontage/Montage',
								'Diskretion' => 'Diskretion',
								'Dummy' => 'Dummy',
								'E-Mail' => 'E-Mail',
								'Entrümpelungen' => 'Entrümpelungen',
								'Facebook' => 'Facebook',
								'FAQ' => 'FAQ',
								'FAQ (Glühbirne)' => 'FAQ (Glühbirne)',
								'Festpreisangebot (Variante 1)' => 'Festpreisangebot (Variante 1)',
								'Festpreisangebot (Variante 2)' => 'Festpreisangebot (Variante 2)',
								'Festpreisangebot (Variante 3)' => 'Festpreisangebot (Variante 3)',
								'Festpreisangebot (Variante 4)' => 'Festpreisangebot (Variante 4)',
								'Fixpreis' => 'Fixpreis',
								'Formular' => 'Formular',
								'Geschäftsauflösung' => 'Geschäftsauflösung',
								'Handwerker' => 'Handwerker',
								'Haus' => 'Haus',
								'Hotelräumung' => 'Hotelräumung',
								'Instagram' => 'Instagram',
								'Kellerräumung' => 'Kellerräumung',
								'Makler' => 'Makler',
								'Messie' => 'Messie',
								'Mobil' => 'Mobil',
								'Räumung (Variante 1)' => 'Räumung (Variante 1)',
								'Räumung (Variante 2)' => 'Räumung (Variante 2)',
								'Reinigung' => 'Reinigung',
								'Reinigung (Kübel)' => 'Reinigung (Kübel)',
								'Renovierung (Variante 1)' => 'Renovierung (Variante 1)',
								'Renovierung (Variante 2)' => 'Renovierung (Variante 2)',
								'Sicherheit (Regenschirm)' => 'Sicherheit (Regenschirm)',
								'Suche' => 'Suche',
								'Teilumzug' => 'Teilumzug',
								'Telefon' => 'Telefon',
								'Tipp' => 'Tipp',
								'Transport' => 'Transport',
								'Uhr' => 'Uhr',
								'Umelt' => 'Umelt',
								'Umzug' => 'Umzug',
								'Umzug/Übersiedelung' => 'Umzug/Übersiedelung',
								'Verlassenschaft (Variante 1)' => 'Verlassenschaft (Variante 1)',
								'Verlassenschaft (Variante 2)' => 'Verlassenschaft (Variante 2)',
								'Verschenken' => 'Verschenken',
								'Vorteile' => 'Vorteile',
								'Wertausgleich' => 'Wertausgleich',
								'Whatsapp' => 'Whatsapp',
								'Wohnungsauflösung' => 'Wohnungsauflösung',
								'Zusatzleistungen' => 'Zusatzleistungen',
							),
							'default_value' => array(
							),
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'placeholder' => '',
							'ajax' => 0,
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_63c5465f2c623',
							'label' => 'link',
							'name' => 'link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '/kontakt',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63e230519acff',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Termin buchen',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63e230805afca',
							'label' => 'Button Link Text',
							'name' => 'button_link_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Schreiben Sie, schicken Sie uns Fotos oder vereinbaren Sie einen Termin für [SITE_TITLE]',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'acfe_group_modal_close' => 0,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
				),
				array(
					'key' => 'field_63b4357302977',
					'label' => 'Ablauf 2',
					'name' => 'ablauf_2',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_63b43604789c9',
							'label' => 'Überschrift',
							'name' => 'uberschrift',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Angebot',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63b43617789ca',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Sie erhalten von uns ein Festpreis-Angebot mit Wertausgleich für alle vereinbarten Kosten ihrer Entrümpelung, Abbau & Transport. Es entstehen für Sie keine versteckten Kosten',
							'placeholder' => '',
							'maxlength' => 250,
							'rows' => '',
							'acfe_textarea_code' => 1,
							'new_lines' => '',
						),
						array(
							'key' => 'field_63b43884b52a5',
							'label' => 'icon',
							'name' => 'icon',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'3. Generation' => '3. Generation',
								'Aktenvernichtung' => 'Aktenvernichtung',
								'Antiquitäten Ankauf' => 'Antiquitäten Ankauf',
								'Antiquitäten Briefmarke' => 'Antiquitäten Briefmarke',
								'Antiquitäten Dosen' => 'Antiquitäten Dosen',
								'Antiquitäten Gemälde' => 'Antiquitäten Gemälde',
								'Antiquitäten Krug' => 'Antiquitäten Krug',
								'Antiquitäten Münzen' => 'Antiquitäten Münzen',
								'Antiquitäten Orden' => 'Antiquitäten Orden',
								'Antiquitäten Religion' => 'Antiquitäten Religion',
								'Antiquitäten Teppich' => 'Antiquitäten Teppich',
								'Antiquitäten Uhr' => 'Antiquitäten Uhr',
								'Barzahlung' => 'Barzahlung',
								'Besichtigung' => 'Besichtigung',
								'Büroräumung' => 'Büroräumung',
								'Dachböden' => 'Dachböden',
								'Demontage' => 'Demontage',
								'Demontage/Montage' => 'Demontage/Montage',
								'Diskretion' => 'Diskretion',
								'Dummy' => 'Dummy',
								'E-Mail' => 'E-Mail',
								'Entrümpelungen' => 'Entrümpelungen',
								'Facebook' => 'Facebook',
								'FAQ' => 'FAQ',
								'FAQ (Glühbirne)' => 'FAQ (Glühbirne)',
								'Festpreisangebot (Variante 1)' => 'Festpreisangebot (Variante 1)',
								'Festpreisangebot (Variante 2)' => 'Festpreisangebot (Variante 2)',
								'Festpreisangebot (Variante 3)' => 'Festpreisangebot (Variante 3)',
								'Festpreisangebot (Variante 4)' => 'Festpreisangebot (Variante 4)',
								'Fixpreis' => 'Fixpreis',
								'Formular' => 'Formular',
								'Geschäftsauflösung' => 'Geschäftsauflösung',
								'Handwerker' => 'Handwerker',
								'Haus' => 'Haus',
								'Hotelräumung' => 'Hotelräumung',
								'Instagram' => 'Instagram',
								'Kellerräumung' => 'Kellerräumung',
								'Makler' => 'Makler',
								'Messie' => 'Messie',
								'Mobil' => 'Mobil',
								'Räumung (Variante 1)' => 'Räumung (Variante 1)',
								'Räumung (Variante 2)' => 'Räumung (Variante 2)',
								'Reinigung' => 'Reinigung',
								'Reinigung (Kübel)' => 'Reinigung (Kübel)',
								'Renovierung (Variante 1)' => 'Renovierung (Variante 1)',
								'Renovierung (Variante 2)' => 'Renovierung (Variante 2)',
								'Sicherheit (Regenschirm)' => 'Sicherheit (Regenschirm)',
								'Suche' => 'Suche',
								'Teilumzug' => 'Teilumzug',
								'Telefon' => 'Telefon',
								'Tipp' => 'Tipp',
								'Transport' => 'Transport',
								'Uhr' => 'Uhr',
								'Umelt' => 'Umelt',
								'Umzug' => 'Umzug',
								'Umzug/Übersiedelung' => 'Umzug/Übersiedelung',
								'Verlassenschaft (Variante 1)' => 'Verlassenschaft (Variante 1)',
								'Verlassenschaft (Variante 2)' => 'Verlassenschaft (Variante 2)',
								'Verschenken' => 'Verschenken',
								'Vorteile' => 'Vorteile',
								'Wertausgleich' => 'Wertausgleich',
								'Whatsapp' => 'Whatsapp',
								'Wohnungsauflösung' => 'Wohnungsauflösung',
								'Zusatzleistungen' => 'Zusatzleistungen',
							),
							'default_value' => array(
							),
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'placeholder' => '',
							'ajax' => 0,
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_63e0fe3af9ad5',
							'label' => 'link',
							'name' => 'link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '/kontakt',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63e230fc03cbf',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Angebot anfordern',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63e2313744663',
							'label' => 'Button Link Text',
							'name' => 'button_link_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Schicken Sie uns die wichtigsten Fakten und wir schreiben Ihnen gerne ein Angebot',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'acfe_group_modal_close' => 0,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
				),
				array(
					'key' => 'field_63b4359c20fbc',
					'label' => 'Ablauf 3',
					'name' => 'ablauf_3',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_63b4373f90aa4',
							'label' => 'Überschrift',
							'name' => 'uberschrift',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Durchführung',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63b4374a90aa5',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'pünktlich und mit allen vereinbarten Leistungen aus unserem Angebot. Nach Abschluss unserer Arbeit erhalten Sie ein besenreines Objekt.',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'acfe_textarea_code' => 0,
						),
						array(
							'key' => 'field_63b438bcb52a6',
							'label' => 'icon',
							'name' => 'icon',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'3. Generation' => '3. Generation',
								'Aktenvernichtung' => 'Aktenvernichtung',
								'Antiquitäten Ankauf' => 'Antiquitäten Ankauf',
								'Antiquitäten Briefmarke' => 'Antiquitäten Briefmarke',
								'Antiquitäten Dosen' => 'Antiquitäten Dosen',
								'Antiquitäten Gemälde' => 'Antiquitäten Gemälde',
								'Antiquitäten Krug' => 'Antiquitäten Krug',
								'Antiquitäten Münzen' => 'Antiquitäten Münzen',
								'Antiquitäten Orden' => 'Antiquitäten Orden',
								'Antiquitäten Religion' => 'Antiquitäten Religion',
								'Antiquitäten Teppich' => 'Antiquitäten Teppich',
								'Antiquitäten Uhr' => 'Antiquitäten Uhr',
								'Barzahlung' => 'Barzahlung',
								'Besichtigung' => 'Besichtigung',
								'Büroräumung' => 'Büroräumung',
								'Dachböden' => 'Dachböden',
								'Demontage' => 'Demontage',
								'Demontage/Montage' => 'Demontage/Montage',
								'Diskretion' => 'Diskretion',
								'Dummy' => 'Dummy',
								'E-Mail' => 'E-Mail',
								'Entrümpelungen' => 'Entrümpelungen',
								'Facebook' => 'Facebook',
								'FAQ' => 'FAQ',
								'FAQ (Glühbirne)' => 'FAQ (Glühbirne)',
								'Festpreisangebot (Variante 1)' => 'Festpreisangebot (Variante 1)',
								'Festpreisangebot (Variante 2)' => 'Festpreisangebot (Variante 2)',
								'Festpreisangebot (Variante 3)' => 'Festpreisangebot (Variante 3)',
								'Festpreisangebot (Variante 4)' => 'Festpreisangebot (Variante 4)',
								'Fixpreis' => 'Fixpreis',
								'Formular' => 'Formular',
								'Geschäftsauflösung' => 'Geschäftsauflösung',
								'Handwerker' => 'Handwerker',
								'Haus' => 'Haus',
								'Hotelräumung' => 'Hotelräumung',
								'Instagram' => 'Instagram',
								'Kellerräumung' => 'Kellerräumung',
								'Makler' => 'Makler',
								'Messie' => 'Messie',
								'Mobil' => 'Mobil',
								'Räumung (Variante 1)' => 'Räumung (Variante 1)',
								'Räumung (Variante 2)' => 'Räumung (Variante 2)',
								'Reinigung' => 'Reinigung',
								'Reinigung (Kübel)' => 'Reinigung (Kübel)',
								'Renovierung (Variante 1)' => 'Renovierung (Variante 1)',
								'Renovierung (Variante 2)' => 'Renovierung (Variante 2)',
								'Sicherheit (Regenschirm)' => 'Sicherheit (Regenschirm)',
								'Suche' => 'Suche',
								'Teilumzug' => 'Teilumzug',
								'Telefon' => 'Telefon',
								'Tipp' => 'Tipp',
								'Transport' => 'Transport',
								'Uhr' => 'Uhr',
								'Umelt' => 'Umelt',
								'Umzug' => 'Umzug',
								'Umzug/Übersiedelung' => 'Umzug/Übersiedelung',
								'Verlassenschaft (Variante 1)' => 'Verlassenschaft (Variante 1)',
								'Verlassenschaft (Variante 2)' => 'Verlassenschaft (Variante 2)',
								'Verschenken' => 'Verschenken',
								'Vorteile' => 'Vorteile',
								'Wertausgleich' => 'Wertausgleich',
								'Whatsapp' => 'Whatsapp',
								'Wohnungsauflösung' => 'Wohnungsauflösung',
								'Zusatzleistungen' => 'Zusatzleistungen',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_63e0fe61f9ad6',
							'label' => 'Link',
							'name' => 'link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '/videos',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63e2315459c3b',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Beispiel ansehen',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_63e2317759c3c',
							'label' => 'Button Link Text',
							'name' => 'button_link_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Sehen Sie Beispiele für [SITE_TITLE] an',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'acfe_group_modal_close' => 0,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-hauptseiten.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-startseite.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
	),
	'active' => true,
	'description' => '',
));

endif;