<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_621dec28252f2',
	'title' => 'Texte für Unterseiten',
	'fields' => array(
		array(
			'key' => 'field_62964dfd0fc0e',
			'label' => 'Status',
			'name' => 'status',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Start' => 'Start',
				'Bearbeitung' => 'Bearbeitung',
				'Inhalte fertig' => 'Inhalte fertig',
				'Überarbeitung' => 'Überarbeitung',
			),
			'allow_null' => 0,
			'other_choice' => 1,
			'save_other_choice' => 1,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'label',
		),
		array(
			'key' => 'field_6220ee4acc4e3',
			'label' => 'Übersichtstexte',
			'name' => 'ubersichtstexte_radom',
			'type' => 'repeater',
			'instructions' => 'Diese Texte werden, wenn kein anderer Text vorhanden - auf der Übersichtsseite des Bezirks angezeigt (der erste Teil \'Leistung in [ORT] - \' ist bereits auf den Übersichtseiten und muss hier nicht eingefügt werden)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'ubersichtstext_radom',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Text hinzufügen',
			'sub_fields' => array(
				array(
					'key' => 'field_6220ef00d9596',
					'label' => 'Übersichtstext',
					'name' => 'ubersichtstext_radom',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
					'acfe_textarea_code' => 0,
				),
			),
		),
		array(
			'key' => 'field_621dec282b692',
			'label' => 'Haupttexte',
			'name' => 'haupttexte_random',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'admin-radom',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_621dec282f89c',
					'label' => 'Überschrift',
					'name' => 'haupttext_uberschrift_radom',
					'type' => 'text',
					'instructions' => '[DL] 
[DL-ENTRUMPELUNG] 
[DASDERUNTERNEHMENWORTE] 
[DIEFIRMAWORTE]

 [UNDWORTE] [SOWIEWORTE] [ISTWORTE] [AUFLOESUNGWORTE] [RAEUMUNGWORTE] [ENTRUEMPELUNGWORTE] [DL-ENTRUMPELUNG]	[SCHNELLWORTE] [PROFIWORTE] [ORDENTLICHWORTE] [PARTNERWORTE] [HELFENWORTE] [MACHTWORTE] [BRAUCHWORTE] [ALLEINWORTE] [RAUMWORTE] [SCHAFFENWORTE] [ORT]',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'admin-radom-heading',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_621dec282f8d4',
					'label' => 'Haupttext',
					'name' => 'haupttext_radom',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'adin-radom_haupttext',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 1,
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Absatz hinzufügen',
					'sub_fields' => array(
						array(
							'key' => 'field_621dec2835e86',
							'label' => 'Text',
							'name' => 'haupttext_absatz_radom',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
							'acfe_textarea_code' => 0,
						),
					),
				),
			),
		),
		array(
			'key' => 'field_621dec284357b',
			'label' => 'Subtexte',
			'name' => 'subtexte_radom',
			'type' => 'repeater',
			'instructions' => '[DL] [DL-ENTRUMPELUNG] [DASDERUNTERNEHMENWORTE] [DIEFIRMAWORTE] [UNDWORTE] [SOWIEWORTE] [ISTWORTE] [AUFLOESUNGWORTE] [RAEUMUNGWORTE] [ENTRUEMPELUNGWORTE] [DL-ENTRUMPELUNG]	[SCHNELLWORTE] [PROFIWORTE] [ORDENTLICHWORTE] [PARTNERWORTE] [HELFENWORTE] [MACHTWORTE] [BRAUCHWORTE] [ALLEINWORTE] [RAUMWORTE] [SCHAFFENWORTE]',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'radom-subtexte',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_621dec28484fa',
					'label' => 'Subtext Überschrift',
					'name' => 'subtext_uberschrift_radom',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_621dec2848532',
					'label' => 'Subtext',
					'name' => 'subtext_radom',
					'type' => 'repeater',
					'instructions' => 'DL] [DL-ENTRUMPELUNG] [DASDERUNTERNEHMENWORTE] [DIEFIRMAWORTE] [UNDWORTE] [SOWIEWORTE] [ISTWORTE] [AUFLOESUNGWORTE] [RAEUMUNGWORTE] [ENTRUEMPELUNGWORTE] [DL-ENTRUMPELUNG] [SCHNELLWORTE] [PROFIWORTE] [ORDENTLICHWORTE] [PARTNERWORTE] [HELFENWORTE] [MACHTWORTE] [BRAUCHWORTE] [ALLEINWORTE] [RAUMWORTE] [SCHAFFENWORTE] [ORT]',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'radom-subtext',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Absatz hinzufügen',
					'sub_fields' => array(
						array(
							'key' => 'field_621dec284f4c0',
							'label' => 'Subtext Absatz',
							'name' => 'subtext_radom_absatz',
							'type' => 'textarea',
							'instructions' => 'DL] [DL-ENTRUMPELUNG] [DASDERUNTERNEHMENWORTE] [DIEFIRMAWORTE] [UNDWORTE] [SOWIEWORTE] [ISTWORTE] [AUFLOESUNGWORTE] [RAEUMUNGWORTE] [ENTRUEMPELUNGWORTE] [DL-ENTRUMPELUNG] [SCHNELLWORTE] [PROFIWORTE] [ORDENTLICHWORTE] [PARTNERWORTE] [HELFENWORTE] [MACHTWORTE] [BRAUCHWORTE] [ALLEINWORTE] [RAUMWORTE] [SCHAFFENWORTE] [ORT]',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'admin-subtext-absatz',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'acfe_textarea_code' => 0,
						),
					),
				),
			),
		),
		array(
			'key' => 'field_63e16d9ede985',
			'label' => 'Textbearbeitung',
			'name' => 'textbearbeitung',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-hauptseiten.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'tags',
		9 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

endif;